# ML Zoomcamp - Homework #1

http://mlzoomcamp.com/

- All the comments were made in portuguese to contribute with people that do not have too much familiarity with english.
- Todos os comentários foram feitos em português para contribuir com o aprendizado de pessoas que não tem tanta familiaridade com a língua inglesa.

- I also want to produce some content in portuguese to learners in Brazil and help to divulge this course.
- Também desejo produzir conteúdo em português para estudantes no Brasil e ajudar a divulgar esse curso!

In [1]:
# importando bibliotecas 
import numpy as np # matrizes
import pandas as pd # tratamento do conjunto de dados

## Questão 1

- Qual a versão do numpy instalada?

In [2]:
np.__version__ # versão corrente da biblioteca numpy

'1.21.6'

In [33]:
# caminho e carregamento do conjunto de dados que será utilizado no trabalho
path = 'https://raw.githubusercontent.com/alexeygrigorev/mlbookcamp-code/master/chapter-02-car-price/data.csv' 
df = pd.read_csv(path)

## Questão 2

- Quantos registros tem no conjunto de dados?

In [ ]:
# formato dos dados em termos de número de linhas (amostras) e número de colunas (variáveis, fatores)
df.shape

(11914, 16)

In [ ]:
df.head()

Make       Model  Year             Engine Fuel Type  Engine HP  \
0  BMW  1 Series M  2011  premium unleaded (required)      335.0   
1  BMW    1 Series  2011  premium unleaded (required)      300.0   
2  BMW    1 Series  2011  premium unleaded (required)      300.0   
3  BMW    1 Series  2011  premium unleaded (required)      230.0   
4  BMW    1 Series  2011  premium unleaded (required)      230.0   

   Engine Cylinders Transmission Type     Driven_Wheels  Number of Doors  \
0               6.0            MANUAL  rear wheel drive              2.0   
1               6.0            MANUAL  rear wheel drive              2.0   
2               6.0            MANUAL  rear wheel drive              2.0   
3               6.0            MANUAL  rear wheel drive              2.0   
4               6.0            MANUAL  rear wheel drive              2.0   

                         Market Category Vehicle Size Vehicle Style  \
0  Factory Tuner,Luxury,High-Performance      Compact         Coupe   
1                     Luxury,Performance      Compact   Convertible   
2                Luxury,High-Performance      Compact         Coupe   
3                     Luxury,Performance      Compact         Coupe   
4                                 Luxury      Compact   Convertible   

   highway MPG  city mpg  Popularity   MSRP  
0           26        19        3916  46135  
1           28        19        3916  40650  
2           28        20        3916  36350  
3           28        18        3916  29450  
4           28        18        3916  34500

## Questão 3 

- Quem são os 3 fabricantes de carro mais frequentes (top3) no conjunto de dados?

In [ ]:
df['Make'].value_counts()[:3]

Chevrolet     1123
Ford           881
Volkswagen     809
Name: Make, dtype: int64

## Questão 4

- Quais os valores únicos de carros da Audi no conjunto de dados?

In [ ]:
# calculando o número de valores únicos dos modelos envolvendo apenas a fabricante Audi 
df[df['Make'] == 'Audi']['Model'].unique().shape

(34,)

## Questão 5

- Quantas colunas do conjunto de dados tem valores faltando?

In [ ]:
# soma dos valores nulos para cada coluna (variável) do dataframe
df.isnull().sum() 

Make                    0
Model                   0
Year                    0
Engine Fuel Type        3
Engine HP              69
Engine Cylinders       30
Transmission Type       0
Driven_Wheels           0
Number of Doors         6
Market Category      3742
Vehicle Size            0
Vehicle Style           0
highway MPG             0
city mpg                0
Popularity              0
MSRP                    0
dtype: int64

## Questão 6

- Encontre o valor da mediana da coluna "Engine Cylinders" no conjunto de dados.
- Em seguida, calcule o valor mais frequente na mesma coluna.
- Use o método "fillna" para preencher os valores ausentes na coluna "Engine Cylinders" com o valor mais frequente encontrado na etapa anterior.
- Por fim, calcule o valor da mediana da coluna "Engine Cylinders" mais uma vez.

Ele mudou?

In [18]:
# descrição detalhada das colunas com valores numéricos
df['Engine Cylinders'].describe()

count    11884.000000
mean         5.628829
std          1.780559
min          0.000000
25%          4.000000
50%          6.000000
75%          6.000000
max         16.000000
Name: Engine Cylinders, dtype: float64

In [19]:
# cálculo da mediana da coluna em questão
df['Engine Cylinders'].median()

6.0

In [26]:
# cálculo da moda da coluna em questão
df['Engine Cylinders'].mode()

0    4.0
dtype: float64

In [36]:
# preenchendo os valores nulos com os valores da moda da respectiva coluna
df['Engine Cylinders'] = df['Engine Cylinders'].fillna(value=df['Engine Cylinders'].mode()[0])

In [37]:
# conferindo a alteração no número de valores nulos
df['Engine Cylinders'].isnull().sum()

0

In [39]:
# observando se o valor da média permaneceu o mesmo após a alteração dos valores nulos
df['Engine Cylinders'].median()

6.0

- O valor permaneceu o mesmo após o tratamento dos valores ausentes. 

## Questão 7

- Selecione todos os carros "Lotus" do conjunto de dados.
- Selecione apenas as colunas "Engine HP", "Engine Cylinders".
- Agora solte todas as linhas duplicadas usando o método drop_duplicates (você deve obter um dataframe com 9 linhas).
- Obtenha a matriz NumPy subjacente. Vamos chamá-la de X.
- Calcule a multiplicação matriz-matriz entre a transposição de X e X. Para obter a transposição, use X.T. Vamos chamar o resultado de XTX.
- Inverta XTX.
- Crie uma matriz y com valores [1100, 800, 750, 850, 1300, 1000, 1000, 1300, 800].
- Multiplique o inverso de XTX com a transposição de X e, em seguida, multiplique o resultado por y. Chame o resultado de w.

Qual é o valor do primeiro elemento de w?

In [4]:
# selecionando apenas a fabricante lotus e as colunas Engine HP e Engine Cylinders. Além disso foi aplicado um método para eliminar valores duplicados
df_lotus = df[df['Make'] == 'Lotus'][["Engine HP", "Engine Cylinders"]].drop_duplicates()
# resultado
df_lotus

Engine HP  Engine Cylinders
3912      189.0               4.0
3913      218.0               4.0
3918      217.0               4.0
4216      350.0               8.0
4257      400.0               6.0
4259      276.0               6.0
4262      345.0               6.0
4292      257.0               4.0
4293      240.0               4.0

In [5]:
X = np.array(df_lotus) # criação de uma matriz a partir do conjunto de dados anterior
X

array([[189.,   4.],
       [218.,   4.],
       [217.,   4.],
       [350.,   8.],
       [400.,   6.],
       [276.,   6.],
       [345.,   6.],
       [257.,   4.],
       [240.,   4.]])

In [6]:
XTX = X.T.dot(X) # produto entre a matriz transposta de X e a própria matriz X
XTX

array([[7.31684e+05, 1.34100e+04],
       [1.34100e+04, 2.52000e+02]])

In [7]:
XTX_inv = np.linalg.inv(XTX) # calculando a matriz inversa de XTX

In [8]:
XTX_inv

array([[ 5.53084235e-05, -2.94319825e-03],
       [-2.94319825e-03,  1.60588447e-01]])

In [9]:
y = np.array([1100, 800, 750, 850, 1300, 1000, 1000, 1300, 800]) 

In [14]:
z = XTX_inv.dot(X.T) # armazenando a multiplicação da matriz inversa de XTX com a transposta de X em uma variável "z"
w = z.dot(y) # calculando o produto da matriz z com o vetor y para obter w

In [17]:
w[0] # primeiro elemento do vetor "w"

4.594944810094551